config/routes.rb
Rails.application.routes.draw do
  # adding the root, devise, GET and POST pages that will be
  # generated on the application 
  devise_for :students
  resources :departments
  resources :unis
  root 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'contact', to: 'home#contact'
  post 'ask_for_contact', to: 'home#ask_for_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  # department entity belongs to uni entity (relation)
  # Adding validation to department name
  belongs_to :uni
  validates :name, :uni, presence: true
  # Adding scope so each student can see only departments he chose
  scope :student_departments, ->(student) { joins(:uni).where(['student_id = ?', student.id]) }
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # Used modules for this devise
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Student entity has many unis (relation)
  # means: a student can choose many unis to apply for
  has_many :unis
end

app/models/uni.rb
class Uni < ApplicationRecord
  # Uni entity belongs to the student entity (relation)
  # Uni entity is related to many department
  # means: Student can apply for many departments for the same uni
  # Adding validation to the uni name
  belongs_to :student
  has_many :departments, dependent: :destroy
  validates :name, presence: true
  validates :name, uniqueness: true
  # Adding scope so each student can see only unis he chose
  scope :student_unis, ->(student) { where(['student_id = ?', student.id]) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  before_action :set_uni, only: [:new, :create]
  before_action :authenticate_student!
  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.student_departments(current_student)
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = @uni.departments.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = @uni.departments.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:uni_id, :name)
    end
    # Method to find the uni using params OR to find uni using strong params
    def set_uni
      @uni = Uni.find_by(id: params[:uni_id]) || Uni.find(department_params[:uni_id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # Empty home method
  def home
  end
  # Empty contact method
  def contact
  end
  # Method generating flash Alert if the student forget to mention
  # his email while contacting our team for enquiries
  # If his email is mentioned, He will recieve a confirmation alert 
  def ask_for_contact
    name = params[:name]
    telephone = params[:telephone]
    email = params[:email]
    country = params[:country]
    university_name = params[:university_name]
    message = params[:message]
    if email.blank?
      flash[:alert] = I18n.t('home.ask_for_contact.add_email')
    else
      ContactMailer.contact_email(email, name, telephone, country, university_name, message).deliver_now
      flash[:notice] = I18n.t('home.ask_for_contact.email_sent')
    end

   redirect_to root_path
  end
end

app/controllers/unis_controller.rb
class UnisController < ApplicationController
  before_action :set_uni, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_student!
  # GET /unis
  # GET /unis.json
  def index
    @unis = Uni.student_unis(current_student)
  end
  # GET /unis/1
  # GET /unis/1.json
  def show
  end
  # GET /unis/new
  def new
    @uni = Uni.new
  end
  # GET /unis/1/edit
  def edit
  end
  # POST /unis
  # POST /unis.json
  def create
    @uni = Uni.new(uni_params)
    @uni.student = current_student

    respond_to do |format|
      if @uni.save
        format.html { redirect_to @uni, notice: 'Uni was successfully created.' }
        format.json { render :show, status: :created, location: @uni }
      else
        format.html { render :new }
        format.json { render json: @uni.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /unis/1
  # PATCH/PUT /unis/1.json
  def update
    respond_to do |format|
      if @uni.update(uni_params)
        format.html { redirect_to @uni, notice: 'Uni was successfully updated.' }
        format.json { render :show, status: :ok, location: @uni }
      else
        format.html { render :edit }
        format.json { render json: @uni.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /unis/1
  # DELETE /unis/1.json
  def destroy
    @uni.destroy
    respond_to do |format|
      format.html { redirect_to unis_url, notice: 'Uni was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  # Private methods 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uni
      @uni = Uni.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def uni_params
      params.require(:uni).permit(:name, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/unis_helper.rb
module UnisHelper
end

app/views/departments/_form.html.erb
<%= form_with(model: department, local: true) do |form| %>
  <% if department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uni_id %>
    <%= @department.uni.name %>
  	<%= form.hidden_field :uni_id, value: @department.uni.id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<!-- localised string refering to the department editing page title -->
<h1><mark><%= t('.edit_department') %></mark></h1><br>
<!-- localised string refering to the department editing page paragraph -->
<p class = "free"> <mark> <%= t('.edit_your_department') %> </mark></p><br>

<%= render 'form', department: @department %>
<!-- adding links for SHOWING and going BACK to department index page -->
<div id= "New">
<%= link_to 'Show', @department %> |
</div>
<div id= "New">
<%= link_to 'Back', departments_path %>
</div>

app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>
<!-- localised string refering to the department title -->
<h1><mark><%= t('.department') %></mark></h1><br><br>
<!-- localised string refering to the departments index page paragraph1 -->
<p class = "free"> <mark> <%= t('.department_list') %> </mark></p><br>
<!-- localised string refering to the departments index page paragraph2 -->
<p class = "free"> <mark> <%= t('.add_uni_first') %> </mark></p>
<!-- Create a DB table holding departments name for each uni -->
<table id="DBtable">
  <thead>
    <tr>
      <th>Uni</th>
      <th>Department</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>
  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.uni.name %></td>
        <td><%= department.name %></td>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/departments/new.html.erb
<h1>New Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<!-- localised string refering to the department show page title -->
<h1><mark><%= t('.show_department') %></mark></h1><br><br>
<!-- localised string refering to the department show page paragraph -->
<p class = "free"> <mark> <%= t('.show_your_department') %> </mark></p>
<!-- Create DB table holding all different departments for the same uni -->
<table id="DBtable">
  <thead>
    <tr>
      <th>
        <strong>Uni:</strong>
      </th>
      <th>
        <strong>Deaprtment name:</strong>
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        <%= @department.uni.name %>
        </td>
      <td>
        <%= @department.name %>
      </td>
  </tr>
</table>
<!-- adding links for EDITING and going BACK to department page -->
<div id= "New">
<%= link_to 'Edit', edit_department_path(@department) %> |
</div>
<div id= "New">
<%= link_to 'Back', departments_path %>
</div>

app/views/home/contact.html.erb
<!-- localised string title for the contact page title -->
<h1><mark><%= t('.contacting_title') %> </mark> </h1>
<br>
<!-- localised string titles for the contact page paragraph -->
<p class = "free"> <mark> <%= t('.contacting_us') %> </mark></p>
<!-- localised string titles for the contact page form -->
<div id = "border"  class = "form">
<%= form_tag ask_for_contact_path, method: 'post' do %>
  <%= label_tag :name, t('.name') %>
  <%= text_field_tag :name, '', title: t('.put_name'), size: 50 %>

  <%= label_tag :telephone, t('.telephone') %>
  <%= telephone_field_tag :telephone, '', title: t('.put_telephone') %>

  <%= label_tag :email, t('.email') %>
  <%= email_field_tag :email, '', title: t('.put_email') %>

  <%= label_tag :name, t('.country') %>
  <%= text_field_tag :name, '', title: t('.put_country'), size: 50 %>

  <%= label_tag :name, t('.university_name') %>
  <%= text_field_tag :name, '', title: t('.put_university_name'), size: 50 %>

  <%= label_tag :message, t('.message') %>
  <%= text_field_tag :message, '', title: t('.put_message'), size: 100 %>

  <div class = "bottona"><%= submit_tag t('.submit') %> </div>
<% end %>
  <br>
  <br>
  <p><b>Certificates requirments </b><span class="glyphicon glyphicon-file"></span></p>
  <form action="/action_page.php"><input type="file" id="myFile" name="filename"></form>

</div>

app/views/home/home.html.erb
<!DOCTYPE html>
<html>
<head>
<h1> <mark> <%= t('.title') %> </mark></h1>
</head>
<body>
<!-- button for showing and hiding the steps students should follow -->
<button class="btn" onclick="myFunction()">Show/Hide steps</button>
<!-- JavaScript for the functioning button -->
<script>
function myFunction() {
  var x = document.getElementById("points");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
</script>
<!-- localised string title for the homePage title -->
<div id="points" class = "all" >
<!-- localised string titles for the homePage note steps -->
<div class="explanation"> <%= t('.explanation') %> </div>
<div class="steps">
<br>
<ul>
<li> <%= t('.Step1') %> </li>
<li> <%= t('.Step2') %> </li>
<li> <%= t('.Step3') %> </li>
<li> <%= t('.Step4') %> </li>
<li> <%= t('.Step5') %> </li>
</ul>
</div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Application information -->
    <title>University Access</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <!-- Calling the header section into the application -->
      <%= render 'section/header' %>
      <!-- Yield for calling all the other pages -->
      <%= yield %>
      <!-- Calling the footer section into the application -->
      <%= render 'section/footer' %>
    </body>
  </html>

app/views/section/_footer.html.erb
<footer>
<p>© <%= t('.name') %> </p>
<p><span class="glyphicon glyphicon-home"> </span> <%= t('.adrress') %> </p>
<p><span class="glyphicon glyphicon-envelope" </span> <%= t('.email') %></p>
<p><span class="glyphicon glyphicon-earphone"</span> <%= t('.phone') %></p>
<span class="glyphicon glyphicon-user"</span><a href="https://www.facebook.com/mohamed.jss.12"> <%= t('.facebook') %>
</footer>

app/views/section/_header.html.erb
<div class="nav_bar">
<nav>
  <a href="/"><span class="glyphicon glyphicon-home"></span> <%= t('.home') %></a> |
  <a href="/contact"><span class="glyphicon glyphicon-envelope"></span> <%= t('.contact') %></a>
  <a href="/unis"><span class="glyphicon glyphicon-tasks"></span> <%= t('.uni') %></a> |
  <a href="/departments"> <%= t('.department') %></a>

  <% if student_signed_in? %>
    <%= "#{current_student.email} |" %>
    <%= link_to t('( profile'), edit_student_registration_path %>
    <%= '|' %>
    <%= link_to t('logout )'), destroy_student_session_path, method: 'delete' %>
  <% else %>
    <%= link_to t('( login'), new_student_session_path %>
    <%= '|' %>
    <%= link_to t('sign_up )'), new_student_registration_path %>
  <% end %>

</nav>
</div>


<% flash.each do |key, value| %>
  <%= content_tag :div, content_tag(:p, value), id: "#{key}" unless value.blank? %>
<% end %>

app/views/unis/_form.html.erb
<%= form_with(model: uni, local: true) do |form| %>
  <% if uni.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(uni.errors.count, "error") %> prohibited this uni from being saved:</h2>

      <ul>
      <% uni.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/unis/edit.html.erb
<!-- localised string refering to the editing title -->
<h1><mark><%= t('.edit_uni') %></mark></h1><br>
<!-- localised string refering to the editing paragraph -->
<p class = "free"> <mark> <%= t('.edit_your_uni') %> </mark></p><br>
<%= render 'form', uni: @uni %>
<!-- adding links for SHOWING and going back to unis page -->
<div id= "New">
<%= link_to 'Show', @uni %> |
</div>
<div id= "New">
<%= link_to 'Back', unis_path %>
</div>

app/views/unis/index.html.erb
<p id="notice"><%= notice %></p>
<!-- localised string refering to the uni index title -->
<h1> <mark> <%= t('.uni') %><mark></h1><br>
  <!-- localised string refering to the uni index paragraph -->
<p class = "free"> <mark> <%= t('.uni_list') %> </mark></p>
<!-- Creating a uni DB table holding unis names -->
<table id="DBtable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @unis.each do |uni| %>
      <tr>
        <td><%= uni.name %></td>
        <td><%= uni.location %></td>
        <td><%= link_to 'Show', uni %></td>
        <td><%= link_to 'Edit', edit_uni_path(uni) %></td>
        <td><%= link_to 'Destroy', uni, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!-- link for ADDING A NEW UNI to the table DB -->
<div id= "NewUni">
<%= link_to 'New University', new_uni_path %>
</div>

app/views/unis/new.html.erb
<h1><mark>New Uni</mark></h1>

<%= render 'form', uni: @uni %>

<%= link_to 'Back', unis_path %>

app/views/unis/show.html.erb
<!-- localised string refering to the showing title -->
<h1> <mark> <%= t('.show_uni') %> <mark></h1><br>
<!-- localised string refering to a paragraph in the showing -->
<p class = "free"> <mark> <%= t('.add_department_to_uni') %> </mark></p>
<!-- DB unis table in the showing page  -->
<table id="DBtable">
  <thead>
    <tr>
      <th><strong>Name:</strong></th>
      <th><strong>Location:</strong></th>
      <th><strong>Departments:</strong></th>
      <th colspan="3">Options</th></tr>
  </thead>

    <tbody>
        <tr>
          <% @uni.departments.each do |department| %>
          <td><%= @uni.name %></td>
          <td><%= @uni.location %></td>
          <td><%= department.name %></td>
          <td><%= link_to 'Show', department %></td>
          <td><%= link_to 'Edit', edit_department_path(department) %></td>
          <td><%= link_to 'Destroy', department, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<!-- links for EDITING and going BACK to unis page -->
<div id= "NewUni">
  <%= link_to 'Add Department', new_department_path(uni_id: @uni) %>
</div>
<br>
<div id= "New">
<%= link_to 'Edit', edit_uni_path(@uni) %>
</div>
<div id= "New">
<%= link_to 'Back', unis_path %>
</div>